theme: jekyll-theme-architect
name: BabyCorgi

# Build settings
permalink: /:categories/:year/:month/:day/:title/


# Markdown  settings
# use Github Flavored Markdown !important
markdown: kramdown
kramdown:
  input: GFM
